/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernanceContract__factory } from "./GovernanceContract__factory";
export { TimeLock__factory } from "./TimeLock__factory";
